// Generated by CoffeeScript 1.4.0
(function() {
  var threeDTV;

  threeDTV = {
    area: $('body'),
    areaPos: $('body').position(),
    movingArea: $('#cube'),
    minHor: 40,
    maxHor: -40,
    minVer: 55,
    maxVer: -30,
    curentX: 0,
    curentY: 0,
    xAngle: 0,
    yAngle: 0,
    transform: 'rotateX(' + 0 + 'deg) rotateY(' + 0 + 'deg)',
    filter: 'custom(url(shaders/detached_tiles.vs) mix(url(shaders/detached_tiles.fs) normal source-atop), 5 5 border-box detached, amount 75.0, t 0.0, transform rotateX(0deg) scale(0.9)) grayscale(0)',
    init: function() {
      threeDTV.stepsCalcul();
      threeDTV.keyMove();
      threeDTV.factsEffect();
      return true;
    },
    stepsCalcul: function() {
      var divHeight, divWidth;
      divWidth = parseInt(threeDTV.area.css('width'));
      divHeight = parseInt(threeDTV.area.css('height'));
      threeDTV.HorStep = divWidth / (threeDTV.minHor + Math.abs(threeDTV.maxHor));
      threeDTV.VerStep = divHeight / (threeDTV.minVer + Math.abs(threeDTV.maxVer));
      threeDTV.mouseMove();
      return true;
    },
    mouseMove: function() {
      threeDTV.area.mousemove(function(e) {
        var math, num;
        threeDTV.curentX = (threeDTV.minHor - ((e.pageX - parseInt(threeDTV.areaPos.left)) / threeDTV.HorStep)).toFixed(1);
        threeDTV.curentY = (threeDTV.minVer - ((e.pageY - parseInt(threeDTV.areaPos.top)) / threeDTV.VerStep)).toFixed(1);
        math = (Math.abs(threeDTV.curentX * 0.01)) + 0.2;
        num = Math.abs(threeDTV.curentY).toFixed(0);
        threeDTV.transform = 'rotateX(' + threeDTV.curentY + 'deg) rotateY(' + threeDTV.curentX + 'deg)';
        threeDTV.movingArea.css('-webkit-transform', threeDTV.transform);
        return true;
      });
      return true;
    },
    keyMove: function() {
      document.addEventListener('keydown', function(e) {
        switch (e.which) {
          case 37:
            threeDTV.yAngle -= 90;
            break;
          case 38:
            threeDTV.xAngle += 90;
            break;
          case 39:
            threeDTV.yAngle += 90;
            break;
          case 40:
            threeDTV.xAngle -= 90;
        }
        threeDTV.movingArea.css('-webkit-transform', "rotateX(" + threeDTV.xAngle + "deg) rotateY(" + threeDTV.yAngle + "deg)");
        return true;
      });
      return true;
    },
    factsEffect: function() {
      var facts;
      facts = $('.fact');
      facts.mouseover(function() {
        console.log('lol');
        $(this).addClass('active');
        return true;
      });
      return true;
    }
  };

  threeDTV.init();

}).call(this);
